meta:
  version: 2
  flow: Classic
  substituting_steps:
    # Padring is used instead of pins
    OpenROAD.IOPlacement: null
    +Odb.SetPowerConnections: OpenROAD.Padring
    
    # Add the seal ring
    +Checker.XOR: KLayout.SealRing
    
    # Run filler insertion
    +KLayout.SealRing: KLayout.FillerGeneration
    
    # Check the density across the layers
    +KLayout.FillerGeneration: KLayout.RunDensity
    +KLayout.RunDensity: Checker.Density
    
    # Due to OpenROAD bug
    # https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
    #TODO OpenROAD.Repair*: null
    
    # Not supported for gf180mcu
    KLayout.DRC: null
    Checker.KLayoutDRC: null
    
    # Save time
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    
    # Stuck, need to investigate...
    #Netgen.LVS: null
    #Checker.LVS: null
    
    Magic.WriteLEF: null # Not needed, save time
    Odb.CheckDesignAntennaProperties: null # Requires LEF

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv

# Enable plugin for better SystemVerilog support
# USE_SLANG: True

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    clk_pad,
    rst_n_pad,

    "bidir\\[0\\].pad",
    "bidir\\[1\\].pad",
    "bidir\\[2\\].pad",
    "bidir\\[3\\].pad",
    "bidir\\[4\\].pad",
    "bidir\\[5\\].pad",

    dvss_south_0,

    "bidir\\[6\\].pad",
    "bidir\\[7\\].pad",
    "bidir\\[8\\].pad",
    "bidir\\[9\\].pad",
    "bidir\\[10\\].pad",
    "bidir\\[11\\].pad",
    "bidir\\[12\\].pad",
    "bidir\\[13\\].pad"
]

PAD_EAST: [
    dvdd_east_0,
    dvss_east_0,

    "bidir\\[14\\].pad",
    "bidir\\[15\\].pad",
    "bidir\\[16\\].pad",
    "bidir\\[17\\].pad",
    "bidir\\[18\\].pad",
    "bidir\\[19\\].pad",
    
    dvdd_east_1,
    dvss_east_1,

    
    "bidir\\[20\\].pad",
    "bidir\\[21\\].pad",
    "bidir\\[22\\].pad",
    "bidir\\[23\\].pad",
    "bidir\\[24\\].pad",
    "bidir\\[25\\].pad",
    
    dvss_east_2,
    dvdd_east_2,
    dvss_east_3,
    dvdd_east_3
]

PAD_NORTH: [
    "bidir\\[41\\].pad",
    "bidir\\[40\\].pad",
    "bidir\\[39\\].pad",
    "bidir\\[38\\].pad",
    "bidir\\[37\\].pad",
    "bidir\\[36\\].pad",
    "bidir\\[35\\].pad",
    "bidir\\[34\\].pad",

    dvss_north_0,

    "bidir\\[33\\].pad",
    "bidir\\[32\\].pad",
    "bidir\\[31\\].pad",
    "bidir\\[30\\].pad",
    "bidir\\[29\\].pad",
    "bidir\\[28\\].pad",
    "bidir\\[27\\].pad",
    "bidir\\[26\\].pad"
]


PAD_WEST: [
    dvdd_west_3,
    dvss_west_3,
    dvdd_west_2,
    dvss_west_2,

    "inputs\\[11\\].pad",
    "inputs\\[10\\].pad",
    "inputs\\[9\\].pad",
    "inputs\\[8\\].pad",
    "inputs\\[7\\].pad",
    "inputs\\[6\\].pad",

    dvdd_west_1,
    dvss_west_1,

    "inputs\\[5\\].pad",
    "inputs\\[4\\].pad",
    "inputs\\[3\\].pad",
    "inputs\\[2\\].pad",

    dvdd_west_0,
    dvss_west_0,
    
    "inputs\\[1\\].pad",
    "inputs\\[0\\].pad"
]

# SDC files
PNR_SDC_FILE: dir::constraint.sdc
SIGNOFF_SDC_FILE: dir::constraint.sdc
FALLBACK_SDC: dir::constraint.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t

# Clock
CLOCK_PORT: clk_PAD
CLOCK_PERIOD: 20

# Floorplanning
FP_SIZING: absolute
# 3880umx5070um including 26um
# for the sealring on all sides
DIE_AREA: [0, 0, 3932, 5122]
CORE_AREA: [442, 442, 3490, 4680]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 35
GRT_ALLOW_CONGESTION: true

# PDN
PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3

# Due to OpenROAD bug
# https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
#PL_TIME_DRIVEN: False
#PL_ROUTABILITY_DRIVEN: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# COMP and Poly2 filler cells need to be 
# flattened to form a "filltrans" layer
- "COMP_fill_cell"
- "Poly2_fill_cell"

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

#MACROS:
#  gf180mcu_ws_ip__id:
#    gds:
#      - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
#    lef:
#      - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
#    nl:
#      - dir::../ip/gf180mcu_ws_ip__id/rtl/gf180mcu_ws_ip__id.v
#    instances:
#      die_id:
#        location: [26, 26]
#        orientation: N
